name: Deploy dailybuild site to server

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH config folder
        run: mkdir -pv ~/.ssh

      - name: Add Known Hosts
        run: |
          echo "${{ secrets.SSH_DEPLOY_HOST_KEY }}" > ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
      
      - name: Add SSH key
        run: |
          touch ~/.ssh/key
          chmod 600 ~/.ssh/key
          echo "${{ secrets.SSH_DEPLOY_RUNNER_KEY }}" > ~/.ssh/key

      - name: Deploy on the remote server
        # -q is required to remove IP leakage when warning about adding the SSH host key that is already kwnown
        run: ssh -q -i ~/.ssh/key "${{ secrets.SSH_DEPLOY_DESTINATION }}"
                                       'cd ~/website/ &&
                                        git pull --force --no-rebase &&
                                        npm install &&
                                        npm run start &&
                                        rm -r /var/www/html/*;
                                        cp -r public/* /var/www/html/'
